colors_dict = {
    "Чёрный": "Qora",
    "Синий": "Ko'k",
    "Серый": "Kulrang",
    "Зелёный": "Yashil",
    "Серебристый": "Kumush",
    "Светло-синий": "Och-ko'k",
    "Красный": "Qizil",
    "Белый": "Oq",
    "Жёлтый": "Sariq",
    "Коричневый": "Jigarrang",
    "Тёмно-красный": "To'q-qizil",
    "Золотистый": "Oltin",
    "Бежевый": "Olov rang",
    "Алый": "To'q-ko'k",
    "Тёмно-серый": "To'q kulrang",
    "Тёмно-голубой": "To'q havorang",
    "Салатовый": "Salat rang",
    "Морской волны": "Ko'kdeniz",
    "Сине-фиолетовый": "Ko'k-binafsha",
    "Баклажановый": "Baqlajon",
    "Зелёный мох": "Yashil-shov",
    "Бордовый": "Bordo",
    "Фиолетовый": "Binafsha"
}
