n = 20
(
    SELECT_LANG,
    GET_NAME,
    GET_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    GET_YEAR,
    GET_MONTH,
    GET_DAY,
    GET_POINT_A,
    GET_POINT_A_HOUSE,
    GET_POINT_B,
    GET_POINT_B_HOUSE,
    CONFIRM_ORDER,
    ORDER_PROCESS,
    GET_FEEDBACK,
    GET_CITY,
    CITY_SETTINGS,

) = range(0, n)